import os
import requests
from src.agent.utils import retry, handle_rate_limit

GEMINI_API_BASE = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"
TIMEOUT = 60


def _call_gemini(prompt: str) -> str:
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        import sys
        print("❌ GEMINI_API_KEY environment variable is not set.")
        sys.exit(1)

    payload = {"contents": [{"parts": [{"text": prompt}]}]}

    def call():
        response = requests.post(
            f"{GEMINI_API_BASE}?key={api_key}",
            json=payload,
            timeout=TIMEOUT
        )
        if response.status_code != 200:
            handle_rate_limit(response.status_code, response.text, "Gemini")
        return response.json()["candidates"][0]["content"]["parts"][0]["text"]

    return retry(call)


def generate_migration_guide(commits: list[str], previous_version: str, new_version: str, repo_name: str) -> str:
    commit_text = "\n".join(f"- {c}" for c in commits)

    prompt = f"""You are a senior technical writer creating a migration guide for a major version upgrade.

Repository: {repo_name}
Upgrading from: {previous_version} to {new_version}

Commits in this release:
{commit_text}

Generate a detailed migration guide including:
1. Overview of what changed and why this is a major release
2. Breaking changes (infer from commits — look for anything that changes APIs, removes features, or changes behavior)
3. Step-by-step migration instructions
4. Before and after code examples if applicable (use generic examples based on the changes)
5. Common issues users might face during migration

Be specific, practical, and developer-friendly.
If no obvious breaking changes are found in commits, say so clearly and provide a general upgrade guide.
"""
    return _call_gemini(prompt)


def generate_marketing_notes(commits: list[str], previous_version: str, new_version: str, repo_name: str) -> str:
    commit_text = "\n".join(f"- {c}" for c in commits)

    prompt = f"""You are a product marketer writing release announcement copy for a major software release.

Repository: {repo_name}
Version: {new_version} (major release from {previous_version})

Changes in this release:
{commit_text}

Generate marketing-friendly release notes including:
1. An exciting headline for the release
2. A compelling 2-3 sentence summary for non-technical users
3. Top 3-5 highlighted new capabilities (focus on user benefits, not technical details)
4. A call to action (e.g. "Upgrade today", "Get started", etc.)

Write in an enthusiastic but professional tone.
Focus on user value and impact, not implementation details.
"""
    return _call_gemini(prompt)


def generate_major_release_notes(commits: list[str], previous_version: str, new_version: str, repo_name: str) -> str:
    commit_text = "\n".join(f"- {c}" for c in commits)

    prompt = f"""You are a technical writer generating comprehensive release notes for a major software version.

Repository: {repo_name}
Major release: {previous_version} → {new_version}

Commits in this release:
{commit_text}

Generate comprehensive release notes including:
1. Release summary (3-4 sentences covering the theme of this major release)
2. Highlights (top new features and improvements)
3. Breaking changes (clearly marked with ⚠️)
4. Full categorized changelog (Features, Bug Fixes, Improvements, Deprecations, Removals)
5. Upgrade notes (brief — full details in migration guide)
6. Changelog entry (single line for CHANGELOG.md)

Be thorough, clear, and professional.
"""
    return _call_gemini(prompt)


def build_major_release_body(
    commits: list[str],
    previous_version: str,
    new_version: str,
    repo_name: str
) -> str:
    """
    Builds the full GitHub Release body for a major release.
    Combines release notes, marketing copy, and migration guide.
    """
    print("   Generating major release notes...")
    release_notes = generate_major_release_notes(commits, previous_version, new_version, repo_name)

    print("   Generating marketing notes...")
    marketing = generate_marketing_notes(commits, previous_version, new_version, repo_name)

    print("   Generating migration guide...")
    migration = generate_migration_guide(commits, previous_version, new_version, repo_name)

    body = f"""# 🚀 {repo_name} {new_version}

{release_notes}

---

## 📣 What's New

{marketing}

---

## 🔄 Migration Guide

{migration}

---

*Release notes generated by [RelaxRelease](https://github.com/siddharth6758/relaxRelease)*
"""
    return body


if __name__ == "__main__":
    sample_commits = [
        "feat!: redesign authentication API — breaking change",
        "feat: add new dashboard with analytics",
        "remove: drop support for Python 3.8",
        "feat: add GraphQL endpoint",
        "fix: resolve memory leak in connection pool",
        "chore: update all dependencies to latest versions",
    ]

    body = build_major_release_body(
        commits=sample_commits,
        previous_version="1.9.0",
        new_version="2.0.0",
        repo_name="relax-release"
    )
    print(body)